name: Create release tarball and attach to tag

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: yarn install --immutable
      - run: yarn build
      - run: |
          version=`git describe --dirty --tags || echo unknown`
          cp -r dist synapse-admin-$version
          tar chvzf dist/synapse-admin-$version.tar.gz synapse-admin-$version
      - uses: softprops/action-gh-release@a74c6b72af54cfa997e81df42d94703d6313a2d0
        with:
          files: dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
